# Generated by Django 3.0.4 on 2020-03-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forma_pago',
            fields=[
                ('fp_id', models.AutoField(primary_key=True, serialize=False)),
                ('fp_nombre', models.CharField(max_length=50)),
                ('tv_descripcion', models.CharField(blank=True, max_length=350, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_mercancia',
            fields=[
                ('tm_id', models.AutoField(primary_key=True, serialize=False)),
                ('tm_nombre', models.CharField(max_length=50)),
                ('tm_peso_max', models.IntegerField()),
                ('tm_peso_min', models.IntegerField()),
                ('tm_precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tm_precio_adicional', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('tm_descripcion', models.CharField(blank=True, max_length=350, null=True)),
                ('tv_estado', models.PositiveSmallIntegerField(max_length=1)),
            ],
        ),
    ]
