# Generated by Django 3.0.4 on 2020-03-28 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
        ('personal', '0001_initial'),
        ('ubicacion', '0003_auto_20200328_1244'),
        ('envio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('des_id', models.AutoField(primary_key=True, serialize=False)),
                ('des_documento', models.CharField(max_length=15)),
                ('des_nombre', models.CharField(max_length=100)),
                ('des_direccion', models.CharField(max_length=50)),
                ('des_telefono', models.CharField(blank=True, max_length=15)),
                ('des_celular', models.CharField(max_length=15)),
                ('mun_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ubicacion.Municipio')),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('env_id', models.AutoField(primary_key=True, serialize=False)),
                ('env_registro', models.DateField()),
                ('env_entrega_estimada', models.DateField()),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('est_id', models.AutoField(primary_key=True, serialize=False)),
                ('est_nombre', models.CharField(max_length=50)),
                ('est_descripcion', models.CharField(blank=True, max_length=350, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tipo_mercancia',
            name='tv_estado',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Mercancia',
            fields=[
                ('mer_id', models.AutoField(primary_key=True, serialize=False)),
                ('mer_peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mer_alto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mer_ancho', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mer_largo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mer_precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mer_precio_envio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cli_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.Cliente')),
                ('des_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='envio.Destinatario')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.Empleado')),
                ('fp_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='envio.Forma_pago')),
                ('tm_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='envio.Tipo_mercancia')),
            ],
        ),
        migrations.CreateModel(
            name='Estado_envio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ee_fecha', models.DateField()),
                ('ee_descripcion', models.CharField(blank=True, max_length=350, null=True)),
                ('env_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='envio.Envio')),
                ('est_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='envio.Estado')),
            ],
        ),
        migrations.AddField(
            model_name='estado',
            name='est_envio',
            field=models.ManyToManyField(through='envio.Estado_envio', to='envio.Envio'),
        ),
        migrations.AddField(
            model_name='envio',
            name='mer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='envio.Mercancia'),
        ),
        migrations.AddField(
            model_name='envio',
            name='veh_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehiculo.Vehiculo'),
        ),
    ]
