# Generated by Django 3.0.4 on 2020-06-06 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envio',
            name='emp_id',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='mer_id',
        ),
        migrations.CreateModel(
            name='Mercancia_envio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='envio.Envio')),
                ('mer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='envio.Mercancia')),
            ],
        ),
    ]
