# Generated by Django 3.0.4 on 2020-05-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercancia',
            name='mer_id',
            field=models.AutoField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
