# Generated by Django 3.0.4 on 2020-06-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envio', '0002_auto_20200606_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercancia',
            name='mer_estado',
            field=models.IntegerField(default=0),
        ),
    ]
