# Generated by Django 3.0.5 on 2020-05-24 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envio', '0002_mercancia_mer_contenido'),
        ('envio', '0002_auto_20200523_1635'),
    ]

    operations = [
    ]
