# Generated by Django 3.0.4 on 2020-05-25 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('dep_id', models.AutoField(primary_key=True, serialize=False)),
                ('dep_nombre', models.CharField(max_length=70)),
                ('dep_codigo', models.IntegerField()),
                ('dep_estado', models.IntegerField(default=0, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('mun_id', models.AutoField(primary_key=True, serialize=False)),
                ('mun_codigo', models.IntegerField()),
                ('mun_nombre', models.CharField(max_length=70)),
                ('mun_estado', models.IntegerField(default=0, max_length=1)),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ubicacion.Departamento')),
            ],
        ),
    ]
