# Generated by Django 3.0.4 on 2020-03-28 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubicacion', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='dep_estado',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='dep_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ubicacion.Departamento'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='mun_estado',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
