# Generated by Django 3.0.4 on 2020-04-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='per_contrasena',
            field=models.TextField(default=512),
            preserve_default=False,
        ),
    ]
