# Generated by Django 3.0.4 on 2020-03-28 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubicacion', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envios_up',
            fields=[
                ('eu_nit', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('eu_nombre', models.CharField(max_length=50)),
                ('eu_telefono', models.CharField(max_length=10)),
                ('eu_email', models.EmailField(max_length=254)),
                ('eu_mision', models.CharField(max_length=600)),
                ('eu_vision', models.CharField(max_length=600)),
                ('eu_fecha_inicio', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('tar_id', models.AutoField(primary_key=True, serialize=False)),
                ('tar_municipal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tar_departamental', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tar_nacional', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('suc_id', models.AutoField(primary_key=True, serialize=False)),
                ('duc_nombre', models.CharField(max_length=50)),
                ('suc_telefono', models.CharField(max_length=10)),
                ('suc_direccion', models.CharField(max_length=50)),
                ('eu_nit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Envios_up')),
                ('mun_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubicacion.Municipio')),
            ],
        ),
    ]
