# Generated by Django 3.0.4 on 2020-03-28 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sucursal',
            old_name='duc_nombre',
            new_name='suc_nombre',
        ),
    ]
