# Generated by Django 3.0.4 on 2020-03-28 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubicacion', '0003_auto_20200328_1244'),
        ('empresa', '0002_auto_20200328_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='eu_nit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresa.Envios_up'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='mun_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ubicacion.Municipio'),
        ),
    ]
